name: Release - Verify
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - alpha/*/*
      - release/*/*
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  try:
    uses: kungfu-systems/workflows/.github/workflows/.release-verify.yml@v2.0-alpha
    with:
      prebuild: false
      build-container-enabled: false
      setup-python-enabled: false
      publish-versioning: false
      publish-aws-ci: false
      publish-aws-user: false
      action-bump-version-ref: v4.0-alpha
  verify:
    needs: try
    runs-on: ubuntu-24.04
    steps:
      - name: report
        run: echo verified
